version: '3.8'

services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:15
    container_name: splabook_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations/001_create_teams_tables.sql:/docker-entrypoint-initdb.d/001_create_teams_tables.sql
      - ./supabase/seed.sql:/docker-entrypoint-initdb.d/002_seed.sql
    networks:
      - supabase_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgREST API
  postgrest:
    image: postgrest/postgrest:v11.1.0
    container_name: splabook_postgrest
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_SERVER_HOST: 0.0.0.0
      PGRST_SERVER_PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - supabase_network

  # nginx リバースプロキシ
  nginx:
    image: nginx:alpine
    container_name: splabook_nginx
    ports:
      - "54321:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgrest
    networks:
      - supabase_network

volumes:
  postgres_data:
    driver: local

networks:
  supabase_network:
    driver: bridge